-- =====================================================================
-- Feedback & Rating table for Panaghiusa Festival 2026
-- Parents/guardians can submit a star rating + comments after the
-- event. Only admins (via the service role key, from the admin
-- dashboard) can read the feedback. Public users can only INSERT.
-- =====================================================================

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  rating smallint not null check (rating between 1 and 5),
  message text,
  parent_name text,
  contact_number text,
  created_at timestamptz not null default now()
);

-- Enable Row Level Security so feedback is NOT publicly readable.
alter table public.feedback enable row level security;

-- Allow anyone (anon + logged-in) to submit feedback.
drop policy if exists "Public can insert feedback" on public.feedback;
create policy "Public can insert feedback"
  on public.feedback
  for insert
  to public
  with check (true);

-- Intentionally no SELECT/UPDATE/DELETE policy for anon/public.
-- The admin dashboard reads this table using the Supabase service
-- role key (lib/supabase-admin.ts), which bypasses RLS entirely.

-- Helpful index for the admin dashboard's default sort order.
create index if not exists feedback_created_at_idx
  on public.feedback (created_at desc);
